services:
  hydra-migrate:
    image: oryd/hydra:latest
    entrypoint: ["sh", "-c"]
    command: 'hydra migrate sql up --yes --dsn "$$DSN"'
    environment:
      - DSN=postgres://postgres:password@postgres:5432/hydra
    depends_on:
      - postgres

  hydra:
    image: oryd/hydra:latest
    command: serve all --dev
    ports:
      - '4444:4444' # public
      - '4445:4445' # admin
    environment:
      - SYSTEM_SECRET=youReallyShouldChangeThis
      - DATABASE_URL=postgres://postgres:password@postgres:5432/hydra?sslmode=disable
      - DSN=postgres://postgres:password@postgres:5432/hydra
      - URLS_SELF_ISSUER=http://localhost:4444/
      - URLS_CONSENT=http://localhost:3000/auth/consent
      - URLS_LOGIN=http://localhost:3000/auth/login
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hydra
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
